Re-former Project Review Request
rloterh/RailsForm pull request #1
Opened 2020-10-30 05:07 UTC by rloterh

- All requirements for this Rails form project are met:
- Created form for User model with form helper 'form_for'
- Form can be validated and throw appropriate error message 
- Form saves validated input correctly

2020-10-30 05:39 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 

Hello!
Great job so far with this project! 👍 
Well done setting up the linters! 💯 
Nice and clean documentation and commits! 👏 
Clean and readable code! 🥇 
However, we need to implement some changes in order to get this project approved 💪 
Kindly check my comments below 👇  and resubmit your project once the changes have been done ⏩ 
## Mandatory changes
- In your views, you should have commented out the previous forms you have built. In this project, we need to be sure you can follow all the steps building formats, since the most basic to the most complex. Kindly, add your previous forms( form and form_tag) and comment them out.
- In your users controller, in the create index, you can use your private method to pass the params, actually, you have this method for that purpose. ie. @user = User.new(user_params), it makes your code cleaner and more readable.
- Make your root page http://localhost:3000/users/new, it will make easier the user to use your app, it is not necessary to land on the rails welcome page
## [OPTIONAL]
- Remember you can use a partial to create a form and use it wherever you want without repeating code
- In your readme file, on the author section, it would be better if you change the links showing your name. ie.Github: @rloterh

2020-10-30 17:23 UTC, rloterh commented
Please, have fixed issues as recommended by first TSE
added comment code, refactor the new method in the controller and fixed the welcome page

2020-10-30 17:50 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
#### Hi @rloterh :+1: you have done a good job so far. However, there is an error when I tried to run the project. Check the image below.

#### _Reviewed by Temitayo Adeleke_

2020-10-30 17:50 UTC, lekegitrepo commented on config/routes.rb
> +  root 'user#new'
- **_This error showed up when I tried to run the project_**

![Action-Controller-Exception-caught](https://user-images.githubusercontent.com/48312803/97739784-505f8100-1aae-11eb-8e7c-8624e90b3e0a.png)

2020-10-31 08:25 UTC, rloterh commented
Resolved issue as per second review
- Application is loading correctly

2020-10-31 08:58 UTC, krys2fa requested changes
### Status: Changes Required ♻️ 
Well done on getting your application to load @rloterh. 👏 
You have also implemented most of the earlier requested changes. Here are a few you missed:

- [ ] [MANDATORY] Create a show action to see the user information, and add an update/edit button that takes you to the edit form to modify the data. Once the user is logged in, it should redirect to its show page and from there to the edit page.

- [ ] [MANDATORY] Add a message or alert when the user is updated and an error message when the update was not successful.

- [ ] [OPTIONAL] In your readme file, on the author section, it would be better if you change the links showing your name. ie.Github: @rloterh

Kindly request another review after making the changes.

Happy Coding,
Chris.

2020-10-31 08:58 UTC, krys2fa commented on app/views/users/new.html.erb
> +<%# form_for %>
- [ ] [MANDATORY] Your form_for implementation is commented out as requested but it still needs to be completed as below:
```
<%#= form_for @user do |u|%> 
<%#= u.label :username %> <%= u.text_field :username%> 
...
...
<%#= u.submit %> 
<%# end %>
```
NB: Remember to fill out all the fields.

2020-11-02 06:12 UTC, rloterh commented
Resolved all issues as per third review

- Application is functioning correctly

2020-11-02 06:48 UTC, javitocor approved these changes
# STATUS APPROVED ♻️ 

Good job with the implemented changes 👍 
Your project is approved 🥳 
Remember to fill up the completion form 📑  and you can move into the next project ⏩ 
Good luck 😺

2020-11-02 16:43 UTC, merged